name: Release

on:
  workflow_dispatch:
    inputs:
      versionNumber:
        description: 'Version number'   
        required: true

jobs:
  build:
    name: Build release
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          
      - name: Install dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --configuration Release --no-restore 

      - name: Publish
        run: dotnet publish ./ColoradoPPDMLoader/ColoradoPPDMLoader.csproj -c Release --self-contained true -r win-x64 -p:PublishSingleFile=true --output ./output

      - name: View content1
        run: dir ./output
        
      - name: Upload ColoradoPPDMLoader Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ColoradoPPDMLoader
          path: ./output/ColoradoPPDMLoader.exe

      - name: Create release
        id: create-new-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.event.inputs.versionNumber }}
          release_name: Release V${{ github.event.inputs.versionNumber }}
          body_path: "./CHANGELOG.md"
